### PR TITLE
Fix check and remove Option.

### PR DESCRIPTION
**Pull request by ltratt**
I noticed that this check:

```
  if layout.size() < tl.size() && layout.align() >= tl.align()
```

appears to be wrong: it should, I believe, involve "||". While thinking about that, I came to the conclusion that since new_from_layout is likely to be in performance critical paths we probably don't want the `Option` involved,
especially since people are only ever unlikely to `unwrap` it. So I've turned the failure of the check into a `panic`.

### CODE REVIEW

**Comment by jacob-hughes** [comment]
Good catch. I agree, panicking inside the method seems more appropriate. LGTM

**Comment by ltratt** [comment]
@vext01 OK for me to rebase this after #14 has merged so that we can try bors'ing it?

**Comment by vext01** [comment]
I don't know anything about this PR, but I'm sure @jacob-hughes wouldn't mind.

If you think he would mind, just make a merge commit that you can squash later.

**Comment by ltratt** [comment]
Rebased.

**Comment by vext01** [comment]
Shall I bors?

**Comment by ltratt** [comment]
Please!

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
That'll serve me right for not testing locally first.

bors try

**Comment by ltratt** [comment]
@vext01 OK to squash?

**Comment by vext01** [comment]
please!

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
