### PR TITLE
Inline allocation calls

### PR DESCRIPTION
**Pull request by jacob-hughes**

### CODE REVIEW

**Comment by ltratt** [comment]
Before we can think about merging this, we need to benchmark it before and after.

**Comment by jacob-hughes** [comment]
I'm happy to benchmark it, but why is it important in order to merge this? These alloc functions are a wrapper around an FFI call to the actual allocator. Inlining is the correct thing to do here because the `NonNull` dance is a thin wrapper around a no-op type.

**Comment by ltratt** [comment]
I assume we're only adding these to enhance performance? However, we don't know if the annotations are actually necessary -- it's possible that the compiler would do the right thing without them. I think we're at the point in the GC's development where performance PRs should have some measurement -- even if it's fairly crude -- to justify themselves.

**Comment by jacob-hughes** [comment]
Agreed, but the inlining pass is mysterious: it's possible that under most circumstances the compiler is inlining these methods, but I'd like to make sure it always does because the `NonNull` dance won't cause icache bloat. In essence, I'll show you the numbers, but I'd argue this should still merge if they don't show any change :)

**Comment by ltratt** [comment]
Ha :p OK, let's see the numbers, and then we can make a decision from there. If we're lucky, the change will be obvious and we won't have to debate!

**Comment by jacob-hughes** [comment]
Here's a quick run of rebench with yksom. It seems that inlining makes a difference in the macro-benchmarks.
```
--------------------------------------------------------------------------------------
  Benchmark     Executor    Suite   Extra   Core   Size   Var   #Samples   Mean (ms)
--------------------------------------------------------------------------------------
  Bounce        inline      micro       2      1                     100   26
  Bounce        no_inline   micro       2      1                     100   26
  BubbleSort    inline      micro       3      1                     100   28
  BubbleSort    no_inline   micro       3      1                     100   28
  DeltaBlue     inline      macro      50      1                      10   23
  DeltaBlue     no_inline   macro      50      1                      10   20
  Dispatch      inline      micro       2      1                     100   17
  Dispatch      no_inline   micro       2      1                     100   17
  Fannkuch      inline      micro       6      1                     100   14
  Fannkuch      no_inline   micro       6      1                     100   14
  Fibonacci     inline      micro       3      1                     100   50
  Fibonacci     no_inline   micro       3      1                     100   53
  FieldLoop     inline      micro       1      1                     100   20
  FieldLoop     no_inline   micro       1      1                     100   20
  IntegerLoop   inline      micro       2      1                     100   32
  IntegerLoop   no_inline   micro       2      1                     100   32
  JsonSmall     inline      macro      10      1                      10   346
  JsonSmall     no_inline   macro      10      1                      10   351
  List          inline      micro       2      1                     100   27
  List          no_inline   micro       2      1                     100   26
  Loop          inline      micro       5      1                     100   42
  Loop          no_inline   micro       5      1                     100   42
  Mandelbrot    inline      micro      30      1                     100   58
  Mandelbrot    no_inline   micro      30      1                     100   61
  NBody         inline      macro    5000      1                      10   364
  NBody         no_inline   macro    5000      1                      10   388
  PageRank      inline      macro      40      1                      10   36
  PageRank      no_inline   macro      40      1                      10   37
  Permute       inline      micro       3      1                     100   26
  Permute       no_inline   micro       3      1                     100   27
  Queens        inline      micro       2      1                     100   23
  Queens        no_inline   micro       2      1                     100   23
  QuickSort     inline      micro       1      1                     100   9
  QuickSort     no_inline   micro       1      1                     100   10
  Recurse       inline      micro       3      1                     100   26
  Recurse       no_inline   micro       3      1                     100   26
  Richards      inline      macro      10      1                      10   5844
  Richards      no_inline   macro      10      1                      10   5902
  Sieve         inline      micro       4      1                     100   41
  Sieve         no_inline   micro       4      1                     100   43
  Storage       inline      micro       1      1                     100   10
  Storage       no_inline   micro       1      1                     100   11
  Sum           inline      micro       2      1                     100   16
  Sum           no_inline   micro       2      1                     100   16
  Towers        inline      micro       2      1                     100   29
  Towers        no_inline   micro       2      1                     100   30
  TreeSort      inline      micro       1      1                     100   22
  TreeSort      no_inline   micro       1      1                     100   23
  WhileLoop     inline      micro      10      1                     100   38
  WhileLoop     no_inline   micro      10      1                     100   37
```

**Comment by ltratt** [comment]
Excellent :)

bors r+

**Pull request merged**
